language: php


matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4
    - php: 8.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_wait composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - bash <(curl -s https://codecov.io/bash)
